services:
  cs2-ban-tracker-bot:
    build: .
    container_name: cs2-ban-tracker-bot_worker

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      # Persist SQLite database
      - ./data:/app/data

    environment:
      - NODE_ENV=production