services:
  cs2-ban-tracker-bot:
    build:
      context: .
      dockerfile: Dockerfile

    # IMPORTANT: une seule image partagée pour tous les dossiers
    image: cs2-ban-tracker-bot:latest

    # Nom dynamique basé sur le dossier (projet compose)
    container_name: cs2-ban-tracker-bot_worker_${COMPOSE_PROJECT_NAME}

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      # DB persistante par dossier
      - ./data:/app/data

    environment:
      NODE_ENV: production